'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Mic, Sparkles, ArrowUp, Volume2, ReceiptText, Info } from 'lucide-react';
import { useKoletPay } from '@/lib/store';
import { PageHead } from '@/components/Shell';
import { amountOf, dateISO, money, remainingOf, shortDate, paidOf } from '@/lib/types';
import { paymentsFor } from '@/lib/metrics';

type Parsed={customerId:string;customerName:string;description:string;amount:number};
function parseInvoice(raw:string,names:{id:string;name:string}[]):Parsed|null{const text=raw.toLowerCase();if(!/(invoice|bill|charge)/.test(text))return null;
 const amountPart=raw.match(/(?:₦|ngn\s*)?([\d,]+(?:\.\d{1,2})?)\s*(k|thousand|m|million)?\b/i);if(!amountPart)return null;
 let amount=Number(amountPart[1].replaceAll(',',''));if(amountPart[2])amount*=['k','thousand'].includes(amountPart[2].toLowerCase())?1000:1000000;
 const found=names.find(c=>text.includes(c.name.toLowerCase())||text.includes(c.name.split(' ')[0].toLowerCase()));if(!found||amount<=0)return null;
 const m=raw.match(/\bfor\s+(.+?)(?:\s+due\b|\s+by\b|[.!]|$)/i);const description=(m?.[1]||'General service').trim();return {customerId:found.id,customerName:found.name,description,amount:Math.round(amount)};
}
type SpeechLike={lang:string;onresult:((ev:{results:{[k:number]:{[k:number]:{transcript:string}}}})=>void)|null;onerror:(()=>void)|null;start:()=>void};
export default function Assistant(){const {data,addInvoice}=useKoletPay();const [text,setText]=useState('');const [reply,setReply]=useState('');const [created,setCreated]=useState('');const [listening,setListening]=useState(false);const [parsed,setParsed]=useState<Parsed|null>(null);
const ask=(input:string)=>{setText(input);setCreated('');const v=input.trim();if(!v){setReply('Enter a question or sample invoice instruction.');return;}const match=parseInvoice(v,data.customers);setParsed(match);const lower=v.toLowerCase();if(match){setReply(`Invoice draft found: ${match.customerName}, ${match.description}, ${money(match.amount)}. Review and create below.`);return;}
 if(/invoice|bill|charge/.test(lower)){setReply('For invoice creation, use a known customer and an amount. Example: "Invoice Sarah 20k for custom mugs."');return;}
 if(/owe|outstanding|overdue|balance/.test(lower)){const list=data.customers.map(c=>({name:c.name,sum:data.invoices.filter(i=>i.customerId===c.id).reduce((s,i)=>s+remainingOf(i),0)})).filter(c=>c.sum>0).sort((a,b)=>b.sum-a.sum);setReply(list.length?`${list.length} customers currently owe ${money(list.reduce((s,c)=>s+c.sum,0))}. Largest open balances: ${list.slice(0,3).map(c=>`${c.name} (${money(c.sum)})`).join(', ')}.`:'No outstanding customer balances in the demo ledger.');return;}
 if(/above|over|greater|more than/.test(lower)){const m=lower.match(/(?:₦|ngn\s*)?(\d[\d,]*)\s*(k|thousand)?/);const threshold=m?Number(m[1].replaceAll(',',''))*(m[2]?1000:1):20000;const payments=data.invoices.flatMap(i=>i.payments.filter(p=>p.amount>threshold).map(p=>({...p,customer:data.customers.find(c=>c.id===i.customerId)})));setReply(`${payments.length} recorded payments are above ${money(threshold)}: ${payments.slice(0,4).map(p=>`${p.customer?.name||'Customer'} ${money(p.amount)}`).join(', ')||'none'}.`);return;}
 if(/revenue|made|received|sales|earn/.test(lower)){const p=lower.includes('today')?'day':lower.includes('year')?'year':'month';const payments=paymentsFor(data,p);setReply(`You received ${money(payments.reduce((s,p)=>s+p.amount,0))} from ${payments.length} payment(s) ${p==='day'?'today':p==='month'?'this month':'this year'}. This total comes from the local transaction logbook.`);return;}
 setReply('I can answer: "Who owes me?", "Revenue this month", "Show payments above ₦20,000", or draft an invoice for an existing customer.');};
const create=()=>{if(!parsed)return;const id=addInvoice({customerId:parsed.customerId,dueAt:dateISO(7),items:[{productId:'',description:parsed.description,unitPrice:parsed.amount,quantity:1}],notes:'Created from KoletPay rule-based demo assistant; review and confirm before sharing.'});setCreated(id);setReply(`Draft ${id} created. You can open it and check all details.`);setParsed(null)};
const voice=()=>{const W=window as typeof window & {SpeechRecognition?:new()=>SpeechLike;webkitSpeechRecognition?:new()=>SpeechLike};const C=W.SpeechRecognition||W.webkitSpeechRecognition;if(!C){setReply('Voice dictation is unavailable in this browser. Type your instruction below instead.');return;}try{const rec=new C();rec.lang='en-NG';rec.onresult=e=>{const transcript=e.results[0][0].transcript;setText(transcript);ask(transcript);setListening(false)};rec.onerror=()=>{setListening(false);setReply('Microphone could not be accessed. Please type the command instead.')};rec.start();setListening(true)}catch{setReply('Unable to start the microphone. You can type the same instruction.');setListening(false)}};
return <><PageHead title="Ask KoletPay" sub="Explore demo business insights, draft invoices using text, or try voice dictation."/><div className="grid-main"><section className="card"><div className="assistant-hero"><span className="assistant-icon"><Sparkles size={30}/></span><h2>Your business assistant</h2><p>Ask about money received, outstanding invoices or create a simple invoice from one sentence.</p></div><div className="stack" style={{marginBottom:20}}><span className="eyebrow">Try one</span><div className="suggestions">{['Who owes me money?','How much revenue this month?','Show payments above ₦20,000','Invoice Sarah 20k for custom mugs'].map(q=><button key={q} onClick={()=>ask(q)} className="btn sm">{q}</button>)}</div></div>{reply&&<div className="note" role="status" style={{lineHeight:1.7,marginBottom:16}}><b>KoletPay:</b> {reply}</div>}{parsed&&<div className="card" style={{background:'#f7f8ff',boxShadow:'none'}}><h3 className="title-sm">Review draft before creating</h3><div className="kv"><span className="key">Customer</span><b>{parsed.customerName}</b></div><div className="kv"><span className="key">Item / service</span><b>{parsed.description}</b></div><div className="kv"><span className="key">Amount</span><b>{money(parsed.amount)}</b></div><div className="kv"><span className="key">Due</span><b>{shortDate(dateISO(7))}</b></div><button className="btn blue block" style={{marginTop:16}} onClick={create}><ReceiptText size={16}/> Create demo invoice</button></div>}{created&&<Link className="btn blue" href={`/invoices/${created}`}>Open {created} →</Link>}
<form onSubmit={e=>{e.preventDefault();ask(text)}} className="assistant-composer"><input className="field" value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about your business or draft an invoice…" aria-label="Ask KoletPay"/><button type="button" aria-label="Dictate using microphone" className={'btn '+(listening?'blue':'')} onClick={voice}><Mic size={18}/>{listening?'Listening':''}</button><button type="submit" className="btn blue" aria-label="Submit message"><ArrowUp size={18}/></button></form></section>
<aside><section className="card"><h2 className="title-sm">What this demo can do</h2><div className="row"><span className="avatar"><ReceiptText size={17}/></span><span className="content"><b>Draft an invoice</b><p>Recognizes known customer names, amounts and descriptions.</p></span></div><div className="row"><span className="avatar"><Volume2 size={17}/></span><span className="content"><b>Optional speech input</b><p>Uses browser speech recognition when available.</p></span></div><div className="row"><span className="avatar"><Info size={17}/></span><span className="content"><b>Search demo data</b><p>Revenue, transactions and outstanding balances.</p></span></div><div className="note" style={{marginTop:20}}>This is a <b>rule-based frontend demonstration</b>, not a connected AI model. It does not send messages or payments automatically.</div></section></aside></div></>}
